from .nodes.luts import NODE_CLASS_MAPPINGS as LUTS_NODE_CLASS_MAPPINGS
from .nodes.luts import NODE_DISPLAY_NAME_MAPPINGS as LUTS_NODE_DISPLAY_NAME_MAPPINGS
from .nodes.waifu2x import NODE_CLASS_MAPPINGS as WAIFU2X_NODE_CLASS_MAPPINGS
from .nodes.waifu2x import NODE_DISPLAY_NAME_MAPPINGS as WAIFU2X_NODE_DISPLAY_NAME_MAPPINGS


NODE_CLASS_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS = {}

NODE_CLASS_MAPPINGS.update(LUTS_NODE_CLASS_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(LUTS_NODE_DISPLAY_NAME_MAPPINGS)

NODE_CLASS_MAPPINGS.update(WAIFU2X_NODE_CLASS_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(WAIFU2X_NODE_DISPLAY_NAME_MAPPINGS)

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']

print(f'\033[34mShibiko AI Nodes: \033[92mLoaded\033[0m')
